var price1 = 25;
var price2 = 35;
var total = price1 + price2;
console.log(total);
var total = price1 - price2;
console.log(total);
var total = price1 * price2;
console.log(total);
var total = price1 / price2;
console.log(total);
var total = price2 % price1;
    total++;
console.log(total);